### ISSUE TITLE
Opening the selfControl app seems to cancel a running scheduled block

### ISSUE THREAD

**Issue by mmckenna91** [andreasgrill/auto-selfcontrol#12]
I'm wondering if this is a known limitation. Normally when opening the selfControl app while a block is running you'll see the time left in the block. When I open the app during a scheduled block by auto-selfcontrol, I'm prompted with the UI that shows when there is no block running and the scheduled block is cancelled. Auto-selfcontrol seems to work fine otherwise.

And thanks for putting this up on github

**Comment by andreasgrill** [comment]
This should be fixed now
