### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by atinwi** [andreasgrill/auto-selfcontrol#18]
ERROR:
The json config file /Applications/auto-selfcontrol-master/config.json is not correctly formatted.The following exception was raised: No JSON object could be decoded

this is the code , just copied and pasted, as per the example, as a test:

    {
    "username": “stan”,
      "selfcontrol-path": "/Applications/SelfControl.app",
    "host-blacklist": [
        "twitter.com",
        "reddit.com"
    ],
    "block-schedules":[
        {
            "weekday": 1,
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 17,
            "end-minute": 0
        },
        {
            "weekday": 2,
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 17,
            "end-minute": 0
        },
        {
            "weekday": 3,
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 17,
            "end-minute": 0
        },
        {
            "weekday": 4,
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 17,
            "end-minute": 0
        },
        {
            "weekday": 5,
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 17,
            "end-minute": 0
        },
        {
            "weekday": 6,
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 17,
            "end-minute": 0
        },
        {
            "weekday": 7,
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 17,
            "end-minute": 0
        }
    ]
}

**Comment by andreasgrill** [comment]
I think the quotations marks around your username are the problem. Could you try it again with straight quotation marks instead of curly ones.

**Comment by atinwi** [comment]
Thanks so much. that was it.

**Comment by adamzerner** [comment]
https://jsonlint.com/ can be used to test the format of `config.json`.
