### ISSUE TITLE
ImportError: No module named Foundation

### ISSUE THREAD

**Issue by a-joyce** [andreasgrill/auto-selfcontrol#19]
When i run
`User-MacBook-Pro:auto-selfcontrol-master user$ sudo python auto-selfcontrol.py`

Traceback (most recent call last):
  File "auto-selfcontrol.py", line 10, in <module>
    from Foundation import NSUserDefaults, CFPreferencesSetAppValue, CFPreferencesAppSynchronize, NSDate
ImportError: No module named Foundation

**Comment by sreecodeslayer** [comment]
Have you looked at the link given in the README at the botom?

The owner seems to address this issue in his README under troubleshooting.

**Comment by sbibauw** [comment]
Actually, the easiest solution (which I think should be the one in the README) is to run original Python installation from Mac OS by running

    sudo /usr/bin/python auto-selfcontrol.py

**Comment by andreasgrill** [comment]
Yeah, that's right!
I'll update the Readme tomorrow!


On 4 Apr 2017, at 17:51, Serge Bibauw <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually, the easiest solution (which I think should be the one in the README) is to run original Python installation from Mac OS by running

sudo /usr/bin/python auto-selfcontrol.py
