### ISSUE TITLE
Couldn't find preference file on first run.

### ISSUE THREAD

**Issue by slambert** [andreasgrill/auto-selfcontrol#2]
I got this in the terminal on first run

    $ python auto-selfcontrol.py
    Password:
    /Library/LaunchDaemons/com.parrot-bytes.auto-selfcontrol.plist: Could not find specified service
    > Installed

Next time I ran it I didn't see it.

**Comment by andreasgrill** [comment]
Thank you, I completely forgot about that. The problem occurs because the script always tries to unload an existing plist before loading it again. However, on the first run there is no existing plist to unload, hence the message. 
It should be fixed now.
