### ISSUE TITLE
Can I run multiple separate schedules?

### ISSUE THREAD

**Issue by SeabassHeyneman** [andreasgrill/auto-selfcontrol#46]
I'd like to have one schedule for the workday which will be a blacklist, and then a separate schedule for late in the evening which will be a whitelist. I'm thinking about installing a second instance of auto-selfcontrol.

Will that work?

**Comment by SeabassHeyneman** [comment]
Would love to create a pull request for auto-selfcontrol to support separate schedules.

Any tips on where to begin in the codebase?

**Comment by SeabassHeyneman** [comment]
@andreasgrill , want to bump this up :)

**Comment by andreasgrill** [comment]
Do you mean creating separate blacklist and white list schedules (that are not overlapping) within the same Auto-SelfControl instance?

**Comment by SeabassHeyneman** [comment]
Yep! Either create a separate blacklist and white list schedule, or create multiple blacklist schedules.

**Comment by SeabassHeyneman** [comment]
Thanks for your help here!

**Comment by andreasgrill** [comment]
I'll look into it.

**Comment by SeabassHeyneman** [comment]
Great! Can I do anything to be helpful?

**Comment by SeabassHeyneman** [comment]
Want to bump this up :)

**Comment by SeabassHeyneman** [comment]
@andreasgrill, let me know in case you plan to look into this. This is my last message, thanks!

**Comment by SeabassHeyneman** [comment]
Marking this closed
