### ISSUE TITLE
Where do we run auto-selfcontrol activate?

### ISSUE THREAD

**Issue by SeabassHeyneman** [andreasgrill/auto-selfcontrol#49]
I tried running `auto-selfcontrol activate` and `python auto-selfcontrol activate` and `python setup.py` and `python auto-selfcontrol.py`, but my config isn't working.

Can you please specify in the docs where we should run `auto-selfcontrol activate`

Thanks!

**Comment by andreasgrill** [comment]
Have you tried starting it with `./auto-selfcontrol activate` ?

**Comment by SeabassHeyneman** [comment]
Thanks, that worked!
