### ISSUE TITLE
Different blacklists at different times?

### ISSUE THREAD

**Issue by nodingneu** [andreasgrill/auto-selfcontrol#57]
00:00 to 14:00 I would like to block youtube.com
14:00 to 18:00 I would like to block stackexchange.com

Does this script support that yet?

**Comment by bradknox** [comment]
Seconded. I have the same question. I'd like to have my normal blacklist for work and then force myself to take a *break* from work at certain times by running a massive blacklist that makes work impossible.

**Comment by Pandoks** [comment]
I created [Hammer Control](https://github.com/Pandoks/hammer-control) which inputs the password into the prompt of the newest version of Self Control. It also lets you define a specific blacklist for every scheduled session which seems like something that you'd like.

**Comment by slambert** [comment]
@Pandoks Thanks for this. We added it to the FAQ!
