### ISSUE TITLE
Auto SelfControl works with SelfControl 3.0.3 and macOS 12.1 

### ISSUE THREAD

**Issue by BDR159** [andreasgrill/auto-selfcontrol#69]
On the readme page of this repository, under "What is it for?", it says "Auto-SelfControl is not compatible yet with macOS 12 and SelfControl 4". This may imply to some people that it doesn't work on macOS 12 altogether, which is not the case. It works for me using SelfControl 3.0.3 and macOS 12.1 (2020 M1 MacBook Air).
I believe it would be clearer if it said that it worked on macOS 12.1 with any version less than 4. Also, does this mean that it works with SelfControl 4 on older versions of macOS less than macOS 12?

**Comment by andreasgrill** [comment]
Thanks!
I updated the Readme.
