### ISSUE TITLE
How to reflect changes on config file?

### ISSUE THREAD

**Issue by vsching** [andreasgrill/auto-selfcontrol#9]
Hi @andreasgrill , thanks for the awesome utility.
I got a few questions about how this works thou.
1. It doesn't seem to pull from my default blacklist list? Does it only use the config file?
2. If i change the blocked website list in the config file, when does it applies? i already did sudo python auto-selfcontrol.py, but still the blocked list doesn't change, does it need to wait until i restart? or when the next scheduled block of time? If so anyway to make it reflect straight away?

Cheers

**Comment by andreasgrill** [comment]
Hi @vsching!
Thank you very much, I'm glad you like it :)
ad 1) In theory it should pull from your black list if you have no `host-blacklist` setting in the config file. However, I don't recommend using this pulling approach anymore, as it appears to be error prone. At the moment, it is not possible for Auto-SelfControl to reliably retrieve the default black list. If this is resolved in the future, I'll happily add it back to the description, but right now it should be avoided.

ad 2) When you add new sites in the config.json, they will be only applied for future schedules. If you want to add sites to the active schedule as well, you have to add them again by starting SelfControl. I know it is a little bit cumbersome to add the sites twice and this is also the reason why I initially wanted to pull the sites from SelfControl directly. Unfortunately, I don't have a better solution at the moment that requires less steps, but I guess I'll figure something out eventually, when I have more time ;)

Cheers,
Andreas

**Comment by vsching** [comment]
Thanks @andreasgrill , it is good enough for now.
But i strongly suggest you put this info in the readme file. It is an awesome utility. However i had a doubt whether it work or not and was about to delete it, luckily I am lazy enough not to remove it.

I think these 2 information is quite important and should be put in the readme file. script will require
i) 1 restart after the first installation, 
ii) and next schedule block for it to work for new site to be added after reapply the the python script after update.

Cheers

**Comment by slambert** [comment]
@vsching good idea - go ahead and make the edits and make a pull request!

**Comment by vsching** [comment]
Sure, will do when I am free 
Cheers

**Comment by andreasgrill** [comment]
@vsching regarding point i) I've now updated auto-selfcontrol to automatically start the blocking when Auto-SelfControl is installed and a schedule is active.
